server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  # Set environment variables
  env REACT_APP_API_URL=https://d92.onrender.com;

  location / {
    try_files $uri /index.html;
  }

  # Handle API requests
  location /api/ {
    proxy_pass https://d92.onrender.com/api/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
